Libraries
```{r}
library(tidyverse)
library(ggbeeswarm) #swarm plot
library(tidytext) #get sentiments
```

Data
```{r}
# BY AUTHOR POSITIONALITY
wm_unnest_auth <- read_csv("data/wm_unnest_auth") %>% select(!1)
wf_unnest_auth <- read_csv("data/wf_unnest_auth")%>% select(!1)
bf_unnest_auth <- read_csv("data/bf_unnest_auth")%>% select(!1)
wm_auth <- read_csv("data/wm_auth") %>% select(!1)
wf_auth <- read_csv("data/wf_auth")%>% select(!1)
bf_auth <- read_csv("data/bf_auth")%>% select(!1)

#all novels together
all_novels_auth <- bind_rows(wm_auth, wf_auth, bf_auth) %>%
  group_by(doc_id) %>%
  mutate(id = row_number()) %>%
  mutate(tot_words = n()) %>%
  ungroup() 
novel_list_auth <- list(wm_auth, wf_auth, bf_auth)
novels_with_stop_list_auth <- list(wm_unnest_auth, wf_unnest_auth, bf_unnest_auth)

# BY PROTAG POSITIONALITY
wm_unnest_char <- read_csv("data/wm_unnest_char")%>% select(!1)
wf_unnest_char <- read_csv("data/wf_unnest_char")%>% select(!1)
bf_unnest_char <- read_csv("data/bf_unnest_char")%>% select(!1)
wm_char <- read_csv("data/wm_char")%>% select(!1)
wf_char <- read_csv("data/wf_char")%>% select(!1)
bf_char <- read_csv("data/bf_char")%>% select(!1)

#all novels together
all_novels_char <- bind_rows(wm_char, wf_char, bf_char) %>%
  group_by(doc_id) %>%
  mutate(id = row_number()) %>%
  mutate(tot_words = n()) %>%
  ungroup() 
novel_list_char <- list(wm_char, wf_char, bf_char)
novels_with_stop_list_char <- list(wm_unnest_char, wf_unnest_char, bf_unnest_char)

# BY GENDER PROTOG
fem_unnest_char_gender <- read_csv("data/fem_unnest_char_gender")
male_unnest_char_gender <- read_csv("data/male_unnest_char_gender")
fem_char_gender <- read_csv("data/fem_char_gender")
male_char_gender <- read_csv("data/male_char_gender")

#all novels together
all_novels_char_gender <- bind_rows(fem_char_gender, male_char_gender) %>%
  group_by(doc_id) %>%
  mutate(id = row_number()) %>%
  mutate(tot_words = n()) %>%
  ungroup() 
novel_list_char_gender <- list(fem_char_gender, male_char_gender)
novels_with_stop_list_char_gender <- list(fem_unnest_char_gender, male_unnest_char_gender)

# BY GENDER AUTH
fem_unnest_auth_gender <- read_csv("data/fem_unnest_auth_gender")%>% select(!1)
male_unnest_auth_gender <- read_csv("data/male_unnest_auth_gender")%>% select(!1)
fem_auth_gender <- read_csv("data/fem_auth_gender")%>% select(!1)
male_auth_gender <- read_csv("data/male_auth_gender")%>% select(!1)

#all novels together
all_novels_auth_gender <- bind_rows(fem_auth_gender, male_auth_gender) %>%
  group_by(doc_id) %>%
  mutate(id = row_number()) %>%
  mutate(tot_words = n()) %>%
  ungroup() 
novel_list_auth_gender <- list(fem_auth_gender, male_auth_gender)
novels_with_stop_list_auth_gender <- list(fem_unnest_auth_gender, male_unnest_auth_gender)

# RACE
w_unnest <- read_csv("data/w_unnest") %>% select(!1)
b_unnest <- read_csv("data/b_unnest")%>% select(!1)
w <- read_csv("data/w")%>% select(!1)
b <- read_csv("data/b")%>% select(!1)

#all novels together
all_novels_race <- bind_rows(w, b) %>%
  group_by(doc_id) %>%
  mutate(id = row_number()) %>%
  mutate(tot_words = n()) %>%
  ungroup() 
novel_list_race <- list(w, b) 
novels_with_stop_list_race <- list(wm_unnest, wf_unnest, bf_unnest)
```



Running shiny app
```{r}


library(shiny)

ui <- fluidPage(

  titlePanel("The Interaction of Mental Health and Positionality in Literature"),

  sidebarLayout(
    
    sidebarPanel(
      # Inputs 
      radioButtons("positionality_choice", label = "What aspects of positionality do you want to investigate?", choices = c("Gender and Race", "Race", "Gender")),
      selectizeInput("viz_choice",
                                label = "What would you like to visualize?", 
                                choices = c("Most common words used", "Sentiment score per novel", "NRC emotion percentages", "Most common mental health words", "Frequency of mental health terms in novel","Frequency of derogatory mental health words","Ratio of derogatory to non-derogatory words","Sentiment +-10 words around mental health words"),
                                selected = "Sentiment score per novel")
    ),
  
    mainPanel(
      tabsetPanel(
        # tabs and reactive visuals
        tabPanel("Project Overview", textOutput("overview")),
        tabPanel("Positionality of Author", plotOutput("plot_1")), 
        tabPanel("Positionality of Protagonist", plotOutput("plot_2")) #,
        #tabPanel("Sentiment Analysis of Each Novel", plotOutput("plot_3"))
        
      )
    )
  )
)
  

server <- function(input, output, session) {
  # #attempt at text outputs
  # output$overview <- renderUI({
  #  str1 <- paste("You have selected")
  #  str2 <- paste("You have chosen a range that goes from")
  #  HTML(paste(str1, str2, sep = '<br/>'))
  #  # HTML('<h1>My First Heading</h1>',
  #        # '<p>My first paragraph.</p>')
  # })
  
  
    # Create a reactive expression
  #chosen input
  #  df <- reactive({
  #   input$positionality_choice
  # })
 
#name
# plotname <- reactive({
#    case_when(input$positionality_choice == "Gender and Race" ~ b
#              input$positionality_choice == "Race" ~  b
#              input$positionality_choice == "Gender" ~ b
#    )
#   })
  
  
#AUTHOR 
  
#TOP WORDS AUTH 
# top_10_words_auth <- function(data_set) {
#   data_set %>%
#     count(doc_id, word) %>%
#   group_by(doc_id) %>%
#   mutate(tot_words = sum(n)) %>%
#   ungroup() %>%
#   group_by(word) %>%
#     mutate(book_count = n()) %>%
#     filter(book_count>=2) %>% #tried 8 and keeps the same :)
#     mutate(freq = n / tot_words) %>%
#     group_by(word) %>%
#     summarize(tot_freq = sum(freq)) %>%
#   slice_max(tot_freq, n=10) %>%
#   mutate(word = fct_reorder(.f = word, .x = tot_freq)) %>%
#   ggplot(aes(tot_freq, word)) +
#   geom_col()
# }
# 
# top_10 <- reactive({
#    case_when(input$positionality_choice == "Gender and Race" ~
#                map(novel_list_auth, top_10_words_auth()),
#              input$positionality_choice == "Race" ~
#                map(novel_list_race, top_10_words_auth()),
#              input$positionality_choice == "Gender" ~
#                map(novel_list_auth_gender, top_10_words_auth())
#    )
#   })
  
     
#SENT PER NOVEL AUTH
     #afinn
afinn_auth <-  reactive({
  case_when(input$positionality_choice == "Gender and Race" ~ 
    all_novels_auth %>% 
   inner_join(get_sentiments("afinn")) %>% 
   group_by(doc_id, positionality, tot_words) %>% 
   summarise(sentiment = sum(value)) %>% 
  mutate(perc = sentiment/tot_words) %>%
   mutate(method = "AFINN") ,
             input$positionality_choice == "Race" ~ 
    all_novels_race %>% 
   inner_join(get_sentiments("afinn")) %>% 
   group_by(doc_id, positionality, tot_words) %>% 
   summarise(sentiment = sum(value)) %>% 
  mutate(perc = sentiment/tot_words) %>%
   mutate(method = "AFINN"),
               input$positionality_choice == "Gender" ~ 
  all_novels_auth_gender %>% 
   inner_join(get_sentiments("afinn")) %>% 
   group_by(doc_id, positionality, tot_words) %>% 
   summarise(sentiment = sum(value)) %>% 
  mutate(perc = sentiment/tot_words) %>%
   mutate(method = "AFINN")
  )
  })


   #bing and nrc
bing_and_nrc_auth <- reactive({
   case_when(input$positionality_choice == "Gender and Race" ~  
  bind_rows(
  all_novels_auth %>% 
    inner_join(get_sentiments("bing")) %>%
    mutate(method = "Bing et al."),
  all_novels_auth %>% 
    inner_join(get_sentiments("nrc") %>% 
                 filter(sentiment %in% c("positive", 
                                         "negative"))
    ) %>%
    mutate(method = "NRC")) %>%
  count(method, doc_id, sentiment, positionality, tot_words) %>%
  spread(sentiment, n, fill = 0) %>%
  mutate(sentiment = positive - negative) %>%
  mutate(perc = sentiment / tot_words),
             input$positionality_choice == "Race" ~ 
                bind_rows(
  all_novels_race %>% 
    inner_join(get_sentiments("bing")) %>%
    mutate(method = "Bing et al."),
  all_novels_race %>% 
    inner_join(get_sentiments("nrc") %>% 
                 filter(sentiment %in% c("positive", 
                                         "negative"))
    ) %>%
    mutate(method = "NRC")) %>%
  count(method, doc_id, sentiment, positionality, tot_words) %>%
  spread(sentiment, n, fill = 0) %>%
  mutate(sentiment = positive - negative) %>%
  mutate(perc = sentiment / tot_words),
             input$positionality_choice == "Gender" ~ 
                bind_rows(
  all_novels_auth_gender %>% 
    inner_join(get_sentiments("bing")) %>%
    mutate(method = "Bing et al."),
  all_novels_auth_gender %>% 
    inner_join(get_sentiments("nrc") %>% 
                 filter(sentiment %in% c("positive", 
                                         "negative"))
    ) %>%
    mutate(method = "NRC")) %>%
  count(method, doc_id, sentiment, positionality, tot_words) %>%
  spread(sentiment, n, fill = 0) %>%
  mutate(sentiment = positive - negative) %>%
  mutate(perc = sentiment / tot_words)
   )
  })

  #Swarm plot
one_sent_per_auth <- reactive({
  ggplot(data = bind_rows(afinn_auth(), bing_and_nrc_auth()),
       aes(x = positionality, y = perc, color = positionality)) +
  geom_beeswarm(cex = 3) +
  facet_wrap(~ method) +
  theme(legend.position = "none") +
   scale_colour_brewer(palette = "Accent") +
  stat_summary(
    geom = "point",
    fun = "mean",
    col = "black",
    size = 1,
    shape = 24,
    fill = "black"
  )
})

 #NRC emotion percentages auth
# nrc_auth <- reactive({
#    case_when(input$positionality_choice == "Gender and Race" ~ 
#                all_novels_auth %>% 
#     inner_join(get_sentiments("nrc")) %>%
#   group_by(positionality) %>%
#   mutate(tot_words = sum(tot_words)) %>%
#   ungroup() %>%
#   count(sentiment, positionality, tot_words) %>%
#   mutate(perc = n/tot_words) %>%
#   ggplot(aes(x=positionality, y=perc)) +
#   facet_wrap(~sentiment) +
#   geom_col()
#              input$positionality_choice == "Race" ~  
#                all_novels_race %>% 
#     inner_join(get_sentiments("nrc")) %>%
#   group_by(positionality) %>%
#   mutate(tot_words = sum(tot_words)) %>%
#   ungroup() %>%
#   count(sentiment, positionality, tot_words) %>%
#   mutate(perc = n/tot_words) %>%
#   ggplot(aes(x=positionality, y=perc)) +
#   facet_wrap(~sentiment) +
#   geom_col()
#              input$positionality_choice == "Gender" ~ 
#                all_novels_auth_gender %>% 
#     inner_join(get_sentiments("nrc")) %>%
#   group_by(positionality) %>%
#   mutate(tot_words = sum(tot_words)) %>%
#   ungroup() %>%
#   count(sentiment, positionality, tot_words) %>%
#   mutate(perc = n/tot_words) %>%
#   ggplot(aes(x=positionality, y=perc)) +
#   facet_wrap(~sentiment) +
#   geom_col()
#    )
#   })
  

#Most common mental health words auth


#Frequency of mental health terms in novel auth 


#Frequency of derogatory mental health words auth


#Ratio of derogatory to non-derogatory words


#sentiment +-10 words around mental health words auth

#-----------------------------------------------------------------------#

#CHARACTER

#top 10 words char


#sent per char

 #afinn - make afin auth df and 3 variables 
afinn_auth <-  reactive({
  case_when(input$positionality_choice == "Gender and Race" ~ 
    all_novels_auth %>% 
   inner_join(get_sentiments("afinn")) %>% 
   group_by(doc_id, positionality, tot_words) %>% 
   summarise(sentiment = sum(value)) %>% 
  mutate(perc = sentiment/tot_words) %>%
   mutate(method = "AFINN") ,
             input$positionality_choice == "Race" ~ 
    all_novels_race %>% 
   inner_join(get_sentiments("afinn")) %>% 
   group_by(doc_id, positionality, tot_words) %>% 
   summarise(sentiment = sum(value)) %>% 
  mutate(perc = sentiment/tot_words) %>%
   mutate(method = "AFINN"),
               input$positionality_choice == "Gender" ~ 
  all_novels_auth_gender %>% 
   inner_join(get_sentiments("afinn")) %>% 
   group_by(doc_id, positionality, tot_words) %>% 
   summarise(sentiment = sum(value)) %>% 
  mutate(perc = sentiment/tot_words) %>%
   mutate(method = "AFINN")
  )
  })


   #bing and nrc char
bing_and_nrc_auth <- reactive({
   case_when(input$positionality_choice == "Gender and Race" ~  
  bind_rows(
  all_novels_auth %>% 
    inner_join(get_sentiments("bing")) %>%
    mutate(method = "Bing et al."),
  all_novels_auth %>% 
    inner_join(get_sentiments("nrc") %>% 
                 filter(sentiment %in% c("positive", 
                                         "negative"))
    ) %>%
    mutate(method = "NRC")) %>%
  count(method, doc_id, sentiment, positionality, tot_words) %>%
  spread(sentiment, n, fill = 0) %>%
  mutate(sentiment = positive - negative) %>%
  mutate(perc = sentiment / tot_words),
             input$positionality_choice == "Race" ~ 
                bind_rows(
  all_novels_race %>% 
    inner_join(get_sentiments("bing")) %>%
    mutate(method = "Bing et al."),
  all_novels_race %>% 
    inner_join(get_sentiments("nrc") %>% 
                 filter(sentiment %in% c("positive", 
                                         "negative"))
    ) %>%
    mutate(method = "NRC")) %>%
  count(method, doc_id, sentiment, positionality, tot_words) %>%
  spread(sentiment, n, fill = 0) %>%
  mutate(sentiment = positive - negative) %>%
  mutate(perc = sentiment / tot_words),
             input$positionality_choice == "Gender" ~ 
                bind_rows(
  all_novels_auth_gender %>% 
    inner_join(get_sentiments("bing")) %>%
    mutate(method = "Bing et al."),
  all_novels_auth_gender %>% 
    inner_join(get_sentiments("nrc") %>% 
                 filter(sentiment %in% c("positive", 
                                         "negative"))
    ) %>%
    mutate(method = "NRC")) %>%
  count(method, doc_id, sentiment, positionality, tot_words) %>%
  spread(sentiment, n, fill = 0) %>%
  mutate(sentiment = positive - negative) %>%
  mutate(perc = sentiment / tot_words)
   )
  })

  #Swarm plot
one_sent_per_auth <- reactive({
  ggplot(data = bind_rows(afinn_auth(), bing_and_nrc_auth()),
       aes(x = positionality, y = perc, color = positionality)) +
  geom_beeswarm(cex = 3) +
  facet_wrap(~ method) +
  theme(legend.position = "none") +
   scale_colour_brewer(palette = "Accent") +
  stat_summary(
    geom = "point",
    fun = "mean",
    col = "black",
    size = 1,
    shape = 24,
    fill = "black"
  )
})

#NRC emotion percentages char
# nrc_char <- reactive({
#    case_when(input$positionality_choice == "Gender and Race" ~ 
#                all_novels_char %>% 
#     inner_join(get_sentiments("nrc")) %>%
#   group_by(positionality) %>%
#   mutate(tot_words = sum(tot_words)) %>%
#   ungroup() %>%
#   count(sentiment, positionality, tot_words) %>%
#   mutate(perc = n/tot_words) %>%
#   ggplot(aes(x=positionality, y=perc)) +
#   facet_wrap(~sentiment) +
#   geom_col()
#              input$positionality_choice == "Race" ~  
#                all_novels_race %>% 
#     inner_join(get_sentiments("nrc")) %>%
#   group_by(positionality) %>%
#   mutate(tot_words = sum(tot_words)) %>%
#   ungroup() %>%
#   count(sentiment, positionality, tot_words) %>%
#   mutate(perc = n/tot_words) %>%
#   ggplot(aes(x=positionality, y=perc)) +
#   facet_wrap(~sentiment) +
#   geom_col()
#              input$positionality_choice == "Gender" ~ 
#                all_novels_char_gender %>% 
#     inner_join(get_sentiments("nrc")) %>%
#   group_by(positionality) %>%
#   mutate(tot_words = sum(tot_words)) %>%
#   ungroup() %>%
#   count(sentiment, positionality, tot_words) %>%
#   mutate(perc = n/tot_words) %>%
#   ggplot(aes(x=positionality, y=perc)) +
#   facet_wrap(~sentiment) +
#   geom_col()
#    )
#   })

#Most common mental health words char


#Frequency of mental health terms in novel char 


#Frequency of derogatory mental health words char


#Ratio of derogatory to non-derogatory char


#sentiment +-10 words around mental health words char

#------------------------------------------------------------------#

  # Use a reactive expression by calling it like a function
#AUTHOR
  output$plot_1 <- renderPlot({
     case_when(#input$viz_choice == "Most common words used" ~ top_10_words_auth(),
               input$viz_choice == "Sentiment score per novel" ~ one_sent_per_auth(),
               input$viz_choice == "NRC emotion percentages" ~ nrc_auth(),
               #input$viz_choice == "Most common mental health words" ~ most_common_mh_auth(),
               #input$viz_choice == "Frequency of mental health terms in novel" ~ freq_mh_auth(),
               #input$viz_choice == "Ratio of derogatory to non-derogatory words" ~ ratio_derog_auth(),
               #input$viz_choice == "Sentiment +-10 words around mental health words" ~ around_mh_auth()
     )
  })
#CHARACTER
  output$plot_2 <- renderPlot({
     case_when(#input$viz_choice == "Most common words used" ~ top_10_char(),
               input$viz_choice == "Sentiment score per novel" ~ one_sent_per_char(),
               input$viz_choice == "NRC emotion percentages" ~ nrc_char(),
               # input$viz_choice == "Most common mental health words" ~ most_common_mh_char(),
               # input$viz_choice == "Frequency of mental health terms in novel" ~ freq_mh_char(),
               # input$viz_choice == "Ratio of derogatory to non-derogatory words" ~ ratio_derog_char(),
               # input$viz_choice == "Sentiment +-10 words around mental health words" ~ around_mh_char()
     )
  })
  
}

shinyApp(ui, server)

```


